USE [MailService]
GO

IF OBJECT_ID('mail.spDeleteMail') IS NOT NULL
	DROP PROCEDURE mail.spDeleteMail
GO

CREATE PROCEDURE mail.spDeleteMail
	@AIDS VARCHAR(MAX) -- []
WITH ENCRYPTION 
AS
BEGIN
	SET NOCOUNT, XACT_ABORT ON;

	DECLARE @IDS VARCHAR(MAX) = @AIDS
		  , @Result INT = 0

	DECLARE @Items TABLE(ID UNIQUEIDENTIFIER)

	INSERT INTO @Items
	SELECT [Value]
	FROM OPENJSON(@IDS)

	BEGIN TRY
		BEGIN TRAN
			DELETE FROM mail.Mail
			WHERE EXISTS(SELECT 1 FROM @Items i WHERE i.ID = mail.Mail.ID)

			SET @Result = @@ROWCOUNT
		COMMIT

	END TRY
	BEGIN CATCH
		;THROW
	END CATCH

	RETURN @Result 
END